version: '3.8'

services:
  backend:
    build: ./backend
    container_name: pbx_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./frontend:/frontend  # <--- Добавили эту строчку
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@pbx_db:5432/asterisk_pbx
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    container_name: pbx_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=asterisk_pbx
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  asterisk:
    image: alpine:latest
    container_name: pbx_asterisk
    command: sleep infinity
    restart: always

volumes:
  postgres_data: