services:
  backend:
    build: ./backend
    container_name: pbx_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./frontend:/frontend
      - ./asterisk/config:/etc/asterisk
      - ./asterisk/sounds:/app/sounds  # <--- Общая папка для записи и конвертации звуков
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@pbx_db:5432/asterisk_pbx
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    container_name: pbx_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=asterisk_pbx
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  asterisk:
    build: ./asterisk
    container_name: asterisk-pbx
    network_mode: host
    volumes:
      - ./asterisk/config:/etc/asterisk
      - ./asterisk/config/certs:/etc/asterisk/certs:ro
      - ./asterisk/sounds:/usr/share/asterisk/sounds/custom  # <--- Asterisk воспроизводит звуки отсюда
    restart: always

  coturn:
    image: coturn/coturn
    container_name: coturn-server
    network_mode: host
    volumes:
      - ./asterisk/coturn/turnserver.conf:/etc/coturn/turnserver.conf
    restart: always

volumes:
  postgres_data: