listening-port=3478
fingerprint
use-auth-secret
static-auth-secret=VERY_SECRET_PASSWORD_123
realm=matrix.fedor-afrin.com
external-ip=158.178.131.112
listening-ip=0.0.0.0
min-port=49152
max-port=65535
verbose
# Добавим эти две строки для совместимости с мобилками
lt-cred-mech
user-quota=100